### PR TITLE
Install cmake version config file

### PR DESCRIPTION
**Pull request by scpeters**
I will wait until #7 is merged.

I plan to do something similar to the following:

* https://bitbucket.org/ignitionrobotics/ign-math/pull-requests/52/add-cmake-version/diff

### CODE REVIEW

**Comment by scpeters** [comment]
This creates and installs a cmake version config file. I've also bumped the minor version so downstream code will be able to find headers with the new pointer typedefs.

**Comment by isucan** [comment]
we should bump the version in the urdfdom pkg as well

**Comment by isucan** [comment]
I don't have an easy means to test this -- can someone test?

**Comment by scpeters** [comment]
I was planning to make another pull request to `urdfdom` that will explicitly require `urdfdom_headers` 0.4 so it can use the new pointer typedefs. I could bump the version in that pull request.

**Comment by scpeters** [comment]
I'll go and make that `urdfdom` pull request so this one will be easier to test.

**Comment by scpeters** [comment]
https://github.com/ros/urdfdom/pull/65

**Comment by scpeters** [comment]
I added a fix for https://github.com/ros/urdfdom/issues/66 as well (missing include file)

**Pull request merged**
