### PR TITLE
fixes degeneracies when doing atan2(0,0)

### PR DESCRIPTION
**Pull request by vrabaud**
This fixes the unit test in urdfdom at https://github.com/ros/urdfdom/issues/49

### CODE REVIEW

**Comment by vrabaud** [comment]
BTW, this is a bad enough bug that a new release should be made, or at least, the patch should be pushed to Ubuntu.

**Comment by isucan** [comment]
+1 for Vincent's comment.
 @esteve, @wjwwood  Do you know who is in charge of the ubuntu release now?

**Comment by wjwwood** [comment]
@j-rivero do you know?

**Comment by j-rivero** [comment]
I am probably the responsible for submitting the updates. If we plan to submit a patch to an already release version (trusty, utopic and vivid) then we need to send a [SRU (Stable Release Update)](https://wiki.ubuntu.com/StableReleaseUpdates) bug, something like we [have done in the past for sdformat](https://bugs.launchpad.net/ubuntu/+source/sdformat/+bug/1338845).

So I would need:

* A standalone test case that demonstrate the error with a different result between the unpatched version and the patched one.
* A short analysis about possible regressions introduced by this patch (check out [Regression Potential] in the [sdformat example](https://bugs.launchpad.net/ubuntu/+source/sdformat/+bug/1338845))
* (Optional) a new release containing this patch, so I fix the development version. I can do it by manually porting the patch, but is less elegant.

Thanks.

**Comment by vrabaud** [comment]
So:

* test is here: https://github.com/ros/urdfdom/blob/master/urdf_parser/test/urdf_unit_test.cpp
* well, none: math is simple, just a specific degeneracy use case is handled. No ABI/API change. No recompilation (pure header implementation).
* I can do a release if needed but more generally, we would need a more recent version for Wily or something.

**Comment by j-rivero** [comment]
Thanks very much Vincent. Here we go: https://bugs.launchpad.net/ubuntu/+source/urdfdom-headers/+bug/1471047.

A new released version to be uploaded to Willy would be very welcome.

**Comment by vrabaud** [comment]
yay, thx ! @isucan , can we have a new release for Willy ?

**Pull request merged**
