### PR TITLE
Cast double to float

### PR DESCRIPTION
**Pull request by sloretz**
This is an attempt to fix a warning on windows. See comment https://github.com/ros/urdfdom_headers/pull/47/files#r233640215

### CODE REVIEW

**Comment by Karsten1987** [comment]
what about using `std::stof`? https://github.com/ros/urdfdom_headers/pull/49
I just saw that my PR came in after this one, so I am happy to close it again.

**Comment by scpeters** [comment]
I'm also setting up an appveyor build for urdfdom so we should get more frequent windows CI testing

* https://github.com/ros/urdfdom/tree/appveyor
* https://ci.appveyor.com/project/scpeters/urdfdom/builds/20312685/job/559m5eqd459wk0kf

Once I have the build working, I'll make a PR and ask @tfoote to add the appveyor webhook

**Comment by scpeters** [comment]
@sloretz it looks like there's still warnings in that CI build?

**Comment by sloretz** [comment]
Ah ooops, I ran CI using urdfdom_headers from master. I'll re-run CI

**Comment by sloretz** [comment]
CI using correct branch [Build Status](https://ci.ros2.org/job/ci_packaging_windows/84/)

**Comment by scpeters** [comment]
@sloretz that build failed

**Comment by sloretz** [comment]
The build failure should be fixed by ament/ament_lint#115

New CI [Build Status](https://ci.ros2.org/job/ci_packaging_windows/)

**Pull request merged**
